title: 'Anas Iqbal, Game Programmer'
description: 'Portfolio of Anas Iqbal, Game Programmer from Pakistan'
url: 'https://anasiqbal.github.io'
email: anasiqbal@outlook.com
logo: /assets/images/AI-Icon.jpg

author:
  name: Anas Iqbal
  email: anasiqbal@outlook.com
  twitter: ianasiqbal
  facebook: anas.iqbal55
  github: anasiqbal
  linkedin: in/anasiqbal55
  spotify: anasiqbal
  udemy: anas-iqbal-2
  steam: anasiqbal

twitter:
  username: ianasiqbal

social:
  name: Anas Iqbal
  links:
    - 'http://www.twitter.com/ianasiqbal'
    - 'https://www.linkedin.com/in/anasiqbal55'
    - 'https://github.com/anasiqbal'
    - 'http://stackoverflow.com/users/1849539/anas-iqbal'
    - 'http://steamcommunity.com/id/anasiqbal'
    - 'https://open.spotify.com/user/anasiqbal'
    - 'https://www.udemy.com/user/anas-iqbal-2'

comments:
  discus: anasiqbal

webmaster_verifications:
  google: n73NqY4YkDgmZyZzCJk6U_61k7hN0qcPe3jM64OY90M
  bing: 3ADDE9727FADDBB6F9B91DCC2ABF80C6

jekyll-mentions:
  base_url: 'https://twitter.com'

markdown: kramdown
theme: minima

gems:
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-mentions
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
