# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Anas Iqbal
designation: Software Engineer
description: The portfolio of Software Engineer/ Gameplay Programmer Anas Iqbal, living and working in Pakistan.
bio: >
  Currently I'm working at <a href="http://www.binexsolutions.com/"><u>Binex Solutions</u></a> on mobile games and applications on Unity3D, iOS and Android. I graduated in <b>2014</b> from <a href="http://www.nu.edu.pk/"><u><abbr title="National University of Computer and Emerging Sciences">NUCES</abbr>, Islamabad, Pakistan</u></a>; with a <b>Computer Science</b> degree. I'm a problem solver at heart, whether its games, apps, puzzles or algorithms.
url: "https://anasiqbal.github.io"

# Contact info
phone:				"+923415188021"
email:				anasiqbal@outlook.com
twitter_name:		ianasiqbal
twitter:			http://www.twitter.com/ianasiqbal
linkedin_name:		in/anasiqbal55
linkedin:			https://www.linkedin.com/in/anasiqbal55
github_name:		anasiqbal
github_url:			https://github.com/anasiqbal
stackoverflow_name:	1849539/anas-iqbal
stackoverflow:		http://stackoverflow.com/users/1849539/anas-iqbal
steam:				anas_iqbal

# Plugins
discus_shortname:	anasiqbal

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
