title               : "Anas Iqbal | Game Programmer Portfolio"
description         : "Game Developer Portfoio of Anas Iqbal, a passionate proffessional "
url                 : "https://anasiqbal.github.io"
logo                : /assets/images/AI-Icon.jpg

author:
  name              : Anas Iqbal
  picture           : "/assets/images/bio-photo.jpeg"
  location          : "Islamabad - Pakistan"
  email             : anasiqbal@outlook.com
  github            : anasiqbal
  linkedin          : anasiqbal55
  stackoverflow     : "1849539/anas-iqbal"
  steam             : anasiqbal

twitter:
  username          : ianasiqbal
  card              : summary

social:
  name              : Anas Iqbal
  links:
    - https://www.facebook.com/anas.iqbal55
    - http://www.twitter.com/ianasiqbal4
    - https://www.linkedin.com/in/anasiqbal55
    - https://github.com/anasiqbal
    - http://stackoverflow.com/users/1849539/anas-iqbal
    - http://steamcommunity.com/id/anasiqbal

comments:
  discus: anasiqbal

webmaster_verifications:
  google: n73NqY4YkDgmZyZzCJk6U_61k7hN0qcPe3jM64OY90M
  bing: 3ADDE9727FADDBB6F9B91DCC2ABF80C6

markdown: kramdown
highlighter: rouge
theme: minima
lsi: false
excerpt_separator: "\n\n"

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Collections
collections:
  artportfolio:
    output: true
    permalink: pretty
  workportfolio:
    output: true
    permalink: pretty
  sideportfolio:
    output: true
    permalink: pretty

include:
  - _pages
exclude:
  - Gemfile
  - Gemfile.lock
  - .sass-cache
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
