title               : "Anas Iqbal"
description         : "Portfolio of Anas Iqbal, Software Engineer (Gameplay) from Pakistan"
url                 : "https://anasiqbal.github.io"
logo                : /assets/images/AI-Icon.jpg

author:
  name              : Anas Iqbal
  avatar            : "/assets/images/bio-photo.jpeg"
  location          : "Islamabad - Pakistan"
  email             : anasiqbal@outlook.com
  twitter           : ianasiqbal
  facebook          : anas.iqbal55
  github            : anasiqbal
  linkedin          : anasiqbal55
  stackoverflow     : "1849539/anas-iqbal"
  spotify           : anasiqbal
  udemy             : anas-iqbal-2
  steam             : anasiqbal

twitter:
  username          : ianasiqbal
facebook:
  username          :
  app_id            :
  publisher         :
og_image            : # Open Graph/Twitter default site image

social:
  type              : Person
  name              : Anas Iqbal
  links:
    - "https://www.facebook.com/anas.iqbal55"
    - "http://www.twitter.com/ianasiqbal"
    - "https://www.linkedin.com/in/anasiqbal55"
    - "https://github.com/anasiqbal"
    - "http://stackoverflow.com/users/1849539/anas-iqbal"
    - "http://steamcommunity.com/id/anasiqbal"
    - "https://open.spotify.com/user/anasiqbal"
    - "https://www.udemy.com/user/anas-iqbal-2"

comments:
  discus: anasiqbal

webmaster_verifications:
  google: n73NqY4YkDgmZyZzCJk6U_61k7hN0qcPe3jM64OY90M
  bing: 3ADDE9727FADDBB6F9B91DCC2ABF80C6

markdown: kramdown
highlighter: rouge
theme: minima
lsi: false
excerpt_separator: "\n\n"

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji

# Collections
collections:
  artportfolio:
    output: true
    permalink: /:collection/:path/
  workportfolio:
    output: true
    permalink: /:collection/:path/
  sideportfolio:
    output: true
    permalink: /:collection/:path/

include:
  - _pages
exclude:
  - Gemfile
  - Gemfile.lock
  - .sass-cache
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
